gui:
  nerdFontsVersion: "2"
  filterMode: fuzzy
  skipDiscardChangeWarning: true

  language: en

  mainPanelSplitMode: horizontal

  theme:
    selectedLineBgColor:
      - reverse
os:
  editPreset: "nvim"
keybinding:
  universal:
    return: <C-c>

